[db]
DB_USER=
DB_PASSWORD=
DB_HOST=
DB_PORT=
DB_NAME=

# モックサービスを使用するかどうか（ローカル開発用）
[mock]
USE_MOCK_SERVICES=false

# リスト内の文字列は必ずダブルクオーテーションで囲うこと
[core]
NAME=
SEARCH_INDEX_NAME_JP_LIST=
SEARCH_INDEX_NAME_ID_LIST=
SEARCH_INDEX_AZURE_ID_LIST=
MODEL_LIST=
DEFAULT_MODEL=

[env]
SEARCH_ENDPOINT=
SEARCH_API_KEY=
SEARCH_MODEL_NAME=
STORAGE_CONNECTION_STRING=
STORAGE_CONTAINER_NAME=
STORAGE_BLOB_SERVICE_ENDPOINT=
EMBEDDING_MODEL_NAME=
AOAI_ENDPOINT=
AOAI_API_KEY=
AOAI_API_VERSION=
SECRET_KEY=
DOCUMENT_INTELLIGENCE_KEY=
DOCUMENT_INTELLIGENCE_ENDPOINT=
SECRET_KEY=

[prompt]
SYSTEM_PROMPT=
HYPOTHETICAL_ANSWER_PROMPT=
